substitutions:
  esp_name: esp-rs485-gw
  bms0_name: bms0
  bms1_name: bms1
  device_description: "Monitor two JK-BMS via UART-TTL"
  external_components_source: github://txubelaxu/esphome-jk-bms@main #github://syssi/esphome-jk-bms@main
  tx_pin_uart_0: GPIO17 #GPIO1 #GPIO16
  rx_pin_uart_0: GPIO16 #GPIO3 #GPIO17

esphome:
  name: ${esp_name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

#esp8266:
#  board: d1_mini

external_components:
    - source: ${external_components_source}
      refresh: 0s
#  - source: ./components
#    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

api:

logger:
  level: INFO #VERY_VERBOSE #VERBOSE #DEBUG #INFO #DEBUG
  tx_buffer_size: 1024

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client
#  log_topic: null

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 1000
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: "JK02_32S"
    rx_timeout: 500ms
    uart_id: uart_0

jk_rs485_bms:
  - id: bms0
    rs485_address: 0x00
    jk_rs485_sniffer_id: sniffer0
    update_interval: 5s
  - id: bms1
    rs485_address: 0x07
    jk_rs485_sniffer_id: sniffer0
    update_interval: 5s

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing:
      name: "${bms0_name} balancing"
    precharging:
      name: "${bms0_name} precharging"
    charging:
      name: "${bms0_name} charging"
    discharging:
      name: "${bms0_name} discharging"
    online_status:
      name: "${bms0_name} online status"
    # ...
    # ...
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    balancing:
      name: "${bms1_name} balancing"
    precharging:
      name: "${bms1_name} precharging"
    charging:
      name: "${bms1_name} charging"
    discharging:
      name: "${bms1_name} discharging"
    online_status:
      name: "${bms1_name} online status"
    # ...

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    balancing:
      name: "${bms0_name} balancing"
    smart_sleep_voltage:
      name: "${bms0_name} smart sleep voltage"
    min_cell_voltage:
      name: "${bms0_name} min cell voltage"
    max_cell_voltage:
      name: "${bms0_name} max cell voltage"
    min_voltage_cell:
      name: "${bms0_name} min voltage cell"
    max_voltage_cell:
      name: "${bms0_name} max voltage cell"
    delta_cell_voltage:
      name: "${bms0_name} delta cell voltage"
    average_cell_voltage:
      name: "${bms0_name} average cell voltage"
    cell_voltage_1:
      name: "${bms0_name} cell voltage 1"
    cell_voltage_2:
      name: "${bms0_name} cell voltage 2"
    cell_voltage_3:
      name: "${bms0_name} cell voltage 3"
    cell_voltage_4:
      name: "${bms0_name} cell voltage 4"
    cell_voltage_5:
      name: "${bms0_name} cell voltage 5"
    cell_voltage_6:
      name: "${bms0_name} cell voltage 6"
    cell_voltage_7:
      name: "${bms0_name} cell voltage 7"
    cell_voltage_8:
      name: "${bms0_name} cell voltage 8"
    cell_voltage_9:
      name: "${bms0_name} cell voltage 9"
    cell_voltage_10:
      name: "${bms0_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms0_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms0_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms0_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms0_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms0_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms0_name} cell voltage 16"
    cell_voltage_17:
      name: "${bms0_name} cell voltage 17"
    cell_voltage_18:
      name: "${bms0_name} cell voltage 18"
    cell_voltage_19:
      name: "${bms0_name} cell voltage 19"
    cell_voltage_20:
      name: "${bms0_name} cell voltage 20"
    cell_voltage_21:
      name: "${bms0_name} cell voltage 21"
    cell_voltage_22:
      name: "${bms0_name} cell voltage 22"
    cell_voltage_23:
      name: "${bms0_name} cell voltage 23"
    cell_voltage_24:
      name: "${bms0_name} cell voltage 24"
    cell_resistance_1:
      name: "${bms0_name} cell resistance 1"
    cell_resistance_2:
      name: "${bms0_name} cell resistance 2"
    cell_resistance_3:
      name: "${bms0_name} cell resistance 3"
    cell_resistance_4:
      name: "${bms0_name} cell resistance 4"
    cell_resistance_5:
      name: "${bms0_name} cell resistance 5"
    cell_resistance_6:
      name: "${bms0_name} cell resistance 6"
    cell_resistance_7:
      name: "${bms0_name} cell resistance 7"
    cell_resistance_8:
      name: "${bms0_name} cell resistance 8"
    cell_resistance_9:
      name: "${bms0_name} cell resistance 9"
    cell_resistance_10:
      name: "${bms0_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms0_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms0_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms0_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms0_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms0_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms0_name} cell resistance 16"
    cell_resistance_17:
      name: "${bms0_name} cell resistance 17"
    cell_resistance_18:
      name: "${bms0_name} cell resistance 18"
    cell_resistance_19:
      name: "${bms0_name} cell resistance 19"
    cell_resistance_20:
      name: "${bms0_name} cell resistance 20"
    cell_resistance_21:
      name: "${bms0_name} cell resistance 21"
    cell_resistance_22:
      name: "${bms0_name} cell resistance 22"
    cell_resistance_23:
      name: "${bms0_name} cell resistance 23"
    cell_resistance_24:
      name: "${bms0_name} cell resistance 24"
    total_voltage:
      name: "${bms0_name} total voltage"
    current:
      name: "${bms0_name} current"
    power:
      name: "${bms0_name} power"
    charging_power:
      name: "${bms0_name} charging power"
    discharging_power:
      name: "${bms0_name} discharging power"
    temperature_sensor_1:
      name: "${bms0_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms0_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms0_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms0_name} temperature sensor 4"
    power_tube_temperature:
      name: "${bms0_name} power tube temperature"
    state_of_charge:
      name: "${bms0_name} state of charge"
    capacity_remaining:
      name: "${bms0_name} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms0_name} total battery capacity setting"
    charging_cycles:
      name: "${bms0_name} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms0_name} total charging cycle capacity"
    total_runtime:
      name: "${bms0_name} total runtime"
    balancing_current:
      name: "${bms0_name} balancing current"
    errors_bitmask:
      name: "${bms0_name} errors bitmask"
    cell_count:
      name: "${bms0_name} cell count"
    cell_overvoltage_protection:
      name: "${bms0_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms0_name} cell overvoltage protection recovery"
    cell_request_charge_voltage:
      name: "${bms0_name} cell request charge voltage"      
    cell_request_float_voltage:
      name: "${bms0_name} cell request float voltage"    
    balance_starting_voltage:
      name: "${bms0_name} balance starting voltage"   
    cell_soc100_voltage:
      name: "${bms0_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms0_name} cell soc0 voltage"  
    cell_undervoltage_protection:
      name: "${bms0_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms0_name} cell undervoltage protection recovery"                     
    cell_power_off_voltage:
      name: "${bms0_name} cell power off voltage"      

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    balancing:
      name: "${bms1_name} balancing"
    smart_sleep_voltage:
      name: "${bms1_name} smart sleep voltage"
    min_cell_voltage:
      name: "${bms1_name} min cell voltage"
    max_cell_voltage:
      name: "${bms1_name} max cell voltage"
    min_voltage_cell:
      name: "${bms1_name} min voltage cell"
    max_voltage_cell:
      name: "${bms1_name} max voltage cell"
    delta_cell_voltage:
      name: "${bms1_name} delta cell voltage"
    average_cell_voltage:
      name: "${bms1_name} average cell voltage"
    cell_voltage_1:
      name: "${bms1_name} cell voltage 1"
    cell_voltage_2:
      name: "${bms1_name} cell voltage 2"
    cell_voltage_3:
      name: "${bms1_name} cell voltage 3"
    cell_voltage_4:
      name: "${bms1_name} cell voltage 4"
    cell_voltage_5:
      name: "${bms1_name} cell voltage 5"
    cell_voltage_6:
      name: "${bms1_name} cell voltage 6"
    cell_voltage_7:
      name: "${bms1_name} cell voltage 7"
    cell_voltage_8:
      name: "${bms1_name} cell voltage 8"
    cell_voltage_9:
      name: "${bms1_name} cell voltage 9"
    cell_voltage_10:
      name: "${bms1_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms1_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms1_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms1_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms1_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms1_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms1_name} cell voltage 16"
    cell_voltage_17:
      name: "${bms1_name} cell voltage 17"
    cell_voltage_18:
      name: "${bms1_name} cell voltage 18"
    cell_voltage_19:
      name: "${bms1_name} cell voltage 19"
    cell_voltage_20:
      name: "${bms1_name} cell voltage 20"
    cell_voltage_21:
      name: "${bms1_name} cell voltage 21"
    cell_voltage_22:
      name: "${bms1_name} cell voltage 22"
    cell_voltage_23:
      name: "${bms1_name} cell voltage 23"
    cell_voltage_24:
      name: "${bms1_name} cell voltage 24"
    cell_resistance_1:
      name: "${bms1_name} cell resistance 1"
    cell_resistance_2:
      name: "${bms1_name} cell resistance 2"
    cell_resistance_3:
      name: "${bms1_name} cell resistance 3"
    cell_resistance_4:
      name: "${bms1_name} cell resistance 4"
    cell_resistance_5:
      name: "${bms1_name} cell resistance 5"
    cell_resistance_6:
      name: "${bms1_name} cell resistance 6"
    cell_resistance_7:
      name: "${bms1_name} cell resistance 7"
    cell_resistance_8:
      name: "${bms1_name} cell resistance 8"
    cell_resistance_9:
      name: "${bms1_name} cell resistance 9"
    cell_resistance_10:
      name: "${bms1_name} cell resistance 10"
    cell_resistance_11:
      name: "${bms1_name} cell resistance 11"
    cell_resistance_12:
      name: "${bms1_name} cell resistance 12"
    cell_resistance_13:
      name: "${bms1_name} cell resistance 13"
    cell_resistance_14:
      name: "${bms1_name} cell resistance 14"
    cell_resistance_15:
      name: "${bms1_name} cell resistance 15"
    cell_resistance_16:
      name: "${bms1_name} cell resistance 16"
    cell_resistance_17:
      name: "${bms1_name} cell resistance 17"
    cell_resistance_18:
      name: "${bms1_name} cell resistance 18"
    cell_resistance_19:
      name: "${bms1_name} cell resistance 19"
    cell_resistance_20:
      name: "${bms1_name} cell resistance 20"
    cell_resistance_21:
      name: "${bms1_name} cell resistance 21"
    cell_resistance_22:
      name: "${bms1_name} cell resistance 22"
    cell_resistance_23:
      name: "${bms1_name} cell resistance 23"
    cell_resistance_24:
      name: "${bms1_name} cell resistance 24"
    total_voltage:
      name: "${bms1_name} total voltage"
    current:
      name: "${bms1_name} current"
    power:
      name: "${bms1_name} power"
    charging_power:
      name: "${bms1_name} charging power"
    discharging_power:
      name: "${bms1_name} discharging power"
    temperature_sensor_1:
      name: "${bms1_name} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms1_name} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms1_name} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms1_name} temperature sensor 4"
    power_tube_temperature:
      name: "${bms1_name} power tube temperature"
    state_of_charge:
      name: "${bms1_name} state of charge"
    capacity_remaining:
      name: "${bms1_name} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms1_name} total battery capacity setting"
    charging_cycles:
      name: "${bms1_name} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms1_name} total charging cycle capacity"
    total_runtime:
      name: "${bms1_name} total runtime"
    balancing_current:
      name: "${bms1_name} balancing current"
    errors_bitmask:
      name: "${bms1_name} errors bitmask"
    cell_count:
      name: "${bms1_name} cell count"
    cell_overvoltage_protection:
      name: "${bms1_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      name: "${bms1_name} cell overvoltage protection recovery"
    cell_request_charge_voltage:
      name: "${bms1_name} cell request charge voltage"      
    cell_request_float_voltage:
      name: "${bms1_name} cell request float voltage"   
    balance_starting_voltage:
      name: "${bms1_name} balance starting voltage"     
    cell_soc100_voltage:
      name: "${bms1_name} cell soc100 voltage" 
    cell_soc0_voltage:
      name: "${bms1_name} cell soc0 voltage"  
    cell_undervoltage_protection:
      name: "${bms1_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      name: "${bms1_name} cell undervoltage protection recovery"   
    cell_power_off_voltage:
      name: "${bms1_name} cell power off voltage"           

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    precharging:
      name: "${bms0_name} precharging"
    charging:
      name: "${bms0_name} charging"
    discharging:
      name: "${bms0_name} discharging"
    balancer:
      name: "${bms0_name} balancer"
    emergency:
      name: "${bms0_name} emergency"
    heating:
      name: "${bms0_name} heating"
    display_always_on:
      name: "${bms0_name} display_always_on"
    charging_float_mode:
      name: "${bms0_name} charging float mode"
    timed_stored_data:
      name: "${bms0_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms0_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms0_name} smart sleep on"
    disable_pcl_module:
      name: "${bms0_name} disable pcl module"

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    precharging:
      name: "${bms1_name} precharging"
    charging:
      name: "${bms1_name} charging"
    discharging:
      name: "${bms1_name} discharging"
    balancer:
      name: "${bms1_name} balancer"
    emergency:
      name: "${bms1_name} emergency"
    heating:
      name: "${bms1_name} heating"
    display_always_on:
      name: "${bms1_name} display_always_on"
    charging_float_mode:
      name: "${bms1_name} charging float mode"
    timed_stored_data:
      name: "${bms1_name} timed stored data"
    disable_temperature_sensors:
      name: "${bms1_name} disable temperature sensors"
    smart_sleep_on:
      name: "${bms1_name} smart sleep on"
    disable_pcl_module:
      name: "${bms1_name} disable pcl module"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms0
    errors:
      name: "${bms0_name} errors"
    operation_mode:
      name: "${bms0_name} operation mode"
    total_runtime_formatted:
      name: "${bms0_name} total runtime formatted"
    battery_type:
      name: "${bms0_name} battery type"

    # ...
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    errors:
      name: "${bms1_name} errors"
    operation_mode:
      name: "${bms1_name} operation mode"
    total_runtime_formatted:
      name: "${bms1_name} total runtime formatted"
    battery_type:
      name: "${bms1_name} battery type"
    # ...
