name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

  lint-clang-format:
    env:
      esphome_directory: esphome
    runs-on: ubuntu-latest
    # cpp lint job runs with esphome-lint docker image so that clang-format-*
    # doesn't have to be installed
    container: esphome/esphome-lint:latest
    steps:
      - uses: actions/checkout@v2
      # Set up the pio project so that the cpp checks know how files are compiled
      # (build flags, libraries etc)

      - name: 💣 Clone esphome project
        run: git clone https://github.com/esphome/esphome.git
      - name: 💣 Copy component into the esphome project
        run: |
          cp -r ../components/* esphome/components/
          git config user.name "ci"
          git config user.email "ci@github.com"
          git add .
          git commit -a -m "Add external component"
        working-directory: ${{ env.esphome_directory }}

      - name: Set up platformio environment
        run: pio init --ide atom
        working-directory: ${{ env.esphome_directory }}

      - name: Run clang-format
        run: script/clang-format -i
        working-directory: ${{ env.esphome_directory }}

      - name: Suggest changes
        run: script/ci-suggest-changes
        working-directory: ${{ env.esphome_directory }}

  lint-clang-tidy:
    env:
      esphome_directory: esphome
    runs-on: ubuntu-latest
    # cpp lint job runs with esphome-lint docker image so that clang-format-*
    # doesn't have to be installed
    container: esphome/esphome-lint:latest
    steps:
      - uses: actions/checkout@v2

      - name: 💣 Clone esphome project
        run: git clone https://github.com/esphome/esphome.git
      - name: 💣 Copy component into the esphome project
        run: |
          cp -r ../components/* esphome/components/
          git config user.name "ci"
          git config user.email "ci@github.com"
          git add .
          git commit -a -m "Add external component"
        working-directory: ${{ env.esphome_directory }}

      # Set up the pio project so that the cpp checks know how files are compiled
      # (build flags, libraries etc)
      - name: Set up platformio environment
        run: pio init --ide atom
        working-directory: ${{ env.esphome_directory }}

      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/clang-tidy.json"
          echo "::add-matcher::.github/workflows/matchers/gcc.json"
      # Can be removed as soon as esphome-lint container is fixed
      - name: Add missing pexpect
        run: pip install pexpect
      - name: Run lint-cpp
        run: script/lint-cpp -c
        working-directory: ${{ env.esphome_directory }}
      - name: Suggest changes
        run: script/ci-suggest-changes
        working-directory: ${{ env.esphome_directory }}

  lint-python:
    env:
      esphome_directory: esphome
    # Don't use the esphome-lint docker image because it may contain outdated requirements.
    # This way, all dependencies are cached via the cache action.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Cache pip modules
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: esphome-pip-3.9-${{ hashFiles('setup.py') }}
          restore-keys: |
            esphome-pip-3.9-

      - name: 💣Clone esphome project
        run: git clone https://github.com/esphome/esphome.git
      - name: 💣Copy component into the esphome project
        run: |
          cp -r ../components/* esphome/components/
          git config user.name "ci"
          git config user.email "ci@github.com"
          git add .
          git commit -a -m "Add external component"
        working-directory: ${{ env.esphome_directory }}

      - name: Set up python environment
        run: script/setup
        working-directory: ${{ env.esphome_directory }}

      - name: Register problem matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/ci-custom.json"
          echo "::add-matcher::.github/workflows/matchers/lint-python.json"
          echo "::add-matcher::.github/workflows/matchers/python.json"

      - name: Lint Custom
        run: script/ci-custom.py -c
        working-directory: ${{ env.esphome_directory }}
      - name: Lint Python
        run: script/lint-python -c
        working-directory: ${{ env.esphome_directory }}

  esphome-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: "3.9"

      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          path: .venv
          # yamllint disable-line rule:line-length
          key: venv-${{ steps.python.outputs.python-version }}
          restore-keys: |
            venv-${{ steps.python.outputs.python-version }}

      - name: Set up virtualenv
        # yamllint disable rule:line-length
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install esphome
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV
        # yamllint enable rule:line-length

      # Use per check platformio cache because checks use different parts
      - name: Cache platformio
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          # yamllint disable-line rule:line-length
          key: platformio-${{ matrix.pio_cache_key }}-${{ hashFiles('platformio.ini') }}

      - name: Write secrets.yaml
        shell: bash
        run: 'echo -e "wifi_ssid: ssid\nwifi_password: password\nmqtt_host: host\nmqtt_username: username\nmqtt_password: password" > secrets.yaml'

      - run: esphome -s external_components_source components config esp32-heltec-balancer-ble-example.yaml
        env:
          # Also cache libdeps, store them in a ~/.platformio subfolder
          PLATFORMIO_LIBDEPS_DIR: ~/.platformio/libdeps
